- .gear/libdomain.spec
- src/entry.c
- src/entry.h
- tests/auto/CMakeLists.txt
- tests/auto/connection_state_machine/connection_state_machine.c
- tests/auto/delete_entry/delete_entry.c
- tests/auto/modify_entry/modify_entry.c
- tests/auto/rename_entry/CMakeLists.txt
- tests/auto/rename_entry/rename_entry.c
- tests/auto/search/search.c
Implement test for rename and modify operations. Fix tests for connection state machine and delete operations.
> feat, fix: create tests for modification and renaming, fix csm and deletion

- .gear/libdomain.spec
> chore: update package version

- src/computer.c
- src/connection_state_machine.c
- src/directory.c
- src/domain.c
- src/domain_p.h
- src/group.c
- src/group.h
- src/organizational_unit.c
- src/organizational_unit.h
- src/user.c
- tests/auto/computer/add_computer/add_computer.c
- tests/auto/group/add_group/add_group.c
- tests/auto/group/delete_group/delete_group.c
- tests/auto/group/mod_group/mod_group.c
- tests/auto/orgranizational_unit/add_ou/add_ou.c
- tests/auto/orgranizational_unit/mod_ou/mod_ou.c
- tests/auto/user/add_user/add_user.c
- tests/auto/user/mod_user/mod_user.c
Add new tests for user, groups and organizational units.
> tests: add tests for users, groups and organizational units

- .gear/libdomain.spec
> chore: update package version in spec file

- tests/CMakeLists.txt
- tests/auto/CMakeLists.txt
- tests/auto/attributes/CMakeLists.txt
- tests/auto/attributes/remove_attribute/CMakeLists.txt
- tests/auto/attributes/remove_attribute/remove_attribute.c
> tests: add attirbute delete test

- src/connection.c
- src/connection.h
- src/connection_state_machine.c
- src/directory.c
- src/directory.h
- tests/auto/CMakeLists.txt
- tests/auto/directory/CMakeLists.txt
- tests/auto/directory/directory.c
This pull request add routines for directory service type detection. We can utilize this later to
perform automated schema loading and while we performing bind to directory.
> feat: add directory type detection routines

- src/CMakeLists.txt
- src/connection.c
- src/connection.h
- src/directory.c
- src/entry.c
- src/request_queue.c
- src/request_queue.h
- tests/auto/CMakeLists.txt
- tests/auto/request_queue/CMakeLists.txt
- tests/auto/request_queue/request_queue.c
Adds request queue to ldap_connection_ctx_t.
> feat: add request queue

- src/request_queue.c
This pull-request fixes documentation for request queue.
> fix: fix documentation for request queue

- .github/workflows/main.yml
- .github/workflows/test.yml
- tests/docker-compose.openldap.yml
- tests/docker-compose.yml
This pull-request provides ability to select test environment. Workflows were also updated to support this change.
> feat: modular test environment

- tests/docker-compose.samba.yml
- tests/docker-compose.yml
- tests/testenv-container/make-test.sh
Adds docker-compose.samba.yml. Adds health-check to OpenLDAP and SambaAD environments.
> feat: modular test environment, module samba

- tests/README.md
Update readme.md in tests folder.
- Documentation update.
> feat: update readme.md for tests

- .github/workflows/test.yml
- script/generate_cert.sh
- tests/README.md
- tests/docker-compose.openldap.yml
- tests/docker-compose.samba.yml
- tests/docker-compose.yml
- tests/openldap-container/slapd.conf
- tests/openldap-container/start-ldap.sh
- tests/samba-container/Dockerfile
- tests/samba-container/provision-samba.sh
- tests/samba-container/smb.conf
This allows us to create testing environments with TLS certificates.
> feat: add tls certificates to the docker environment

- src/computer.c
- src/computer.h
- tests/auto/computer/add_computer/add_computer.c
- tests/auto/computer/delete_computer/delete_computer.c
- tests/auto/computer/mod_computer/mod_computer.c
- tests/auto/computer/rename_computer/rename_computer.c
- tests/openldap-container/domain.alt.ldif
This allows us to edit device entries in openldap.
> feat: add support of computer entries in openldap

- src/domain.c
- tests/auto/anonymous/anonymous.c
Add implementation of anonymous bind test.
> feat: implement anonymous bind test

- src/CMakeLists.txt
- src/attribute.c
- src/attribute.h
- src/domain.c
- src/domain_p.h
- src/entry.h
- tests/auto/attributes/remove_attribute/remove_attribute.c
> Remove attr

- src/user.c
- src/user.h
- tests/auto/user/block_user/block_user.c
- tests/auto/user/unblock_user/unblock_user.c
- tests/openldap-container/domain.alt.ldif
- tests/openldap-container/slapd.conf
Implement user blocking and unblocking for openldap.
> feat: implement user blocking and unblocking for openldap

- src/connection.c
- src/connection.h
Implement network timeout and search time limit ldap options.
Closes # (issue)
> feat: implement network timeout and search timelimit ldap options

- .gear/libdomain.spec
> chore: add fixes in spec file

- src/CMakeLists.txt
- src/schema.c
- src/schema.h
- src/schema_p.h
- tests/auto/CMakeLists.txt
- tests/auto/schema/CMakeLists.txt
- tests/auto/schema/schema.c
- tests/auto/schema/schema_attributetype.c
- tests/auto/schema/schema_new.c
- tests/auto/schema/schema_objectclass.c
- tests/auto/schema/schema_tests.h
Implement ldap schema object and it's tests. Add tests for objectclasses and attributetypes.
> feat: implement ldap schema object and it's tests

- .github/workflows/main.yml
- tests/auto/add_entry/add_entry.c
- tests/auto/delete_entry/delete_entry.c
- tests/auto/modify_entry/modify_entry.c
- tests/auto/rename_entry/rename_entry.c
- tests/openldap-container/Dockerfile
- tests/openldap-container/domain.alt.ldif
- tests/openldap-container/slapd.conf
Add sisyphus test environment.
> feat: add sisyphus test environment

- .gear/libdomain.spec
> chore: update version in spec file

- tests/auto/configure/configure.c
Add new information messages to configure test. Add new return value checks.
> feat: improve configure test

- tests/auto/timeout/timeout.c
> feat: implement timeout test

- script/create-test-data.ps
Add power shell script to create test data in Windows domain.
> feat: add power shell script to create test data

- .gear/libdomain.spec
Update version of the library.
> feat: udapte version in spec file

- .gear/libdomain.spec
- Dockerfile
- src/CMakeLists.txt
- src/connection.c
- src/connection.h
- src/directory.c
- src/domain.c
- src/domain.h
- src/entry.c
- src/entry.h
- src/entry_p.h
- tests/auto/CMakeLists.txt
- tests/auto/anonymous/anonymous.c
- tests/auto/common/test_common.c
- tests/auto/entry_utils/CMakeLists.txt
- tests/auto/entry_utils/entry_add_attribute.c
- tests/auto/entry_utils/entry_get_attribute.c
- tests/auto/entry_utils/entry_get_attributes.c
- tests/auto/entry_utils/entry_new.c
- tests/auto/entry_utils/entry_utils.c
- tests/auto/entry_utils/entry_utils.h
- tests/auto/search/search.c
- tests/auto/tls/tls.c
- tests/testenv-container/Dockerfile
Add wrapper around LDAPMessage.
> feat: refactor ldap search

- .gear/libdomain.spec
- src/connection.c
- src/connection.h
- src/connection_state_machine.c
- tests/auto/bind/bind.c
- tests/auto/directory/directory.c
- tests/auto/reconnect/reconnect.c
- tests/auto/user/add_user/add_user.c
- Perform test cleanup.
- Implement reconnect test.
- Add Russian test data.
> feat: implement new tests

- .gear/libdomain.spec
- tests/auto/attributes/remove_attribute/remove_attribute.c
- tests/auto/search/search.c
> fix: various fixes

- .github/workflows/publish-api-docs.yml
- src/domain.c
- src/entry.c
- src/entry.h
- tests/auto/entry/delete_entry/delete_entry.c
Rename delete function to avoid name collision with c++ delete operator.
> feat: rename delete function

- .gear/libdomain.spec
- script/create-test-data.ps1
- tests/auto/computer/add_computer/add_computer.c
- tests/auto/computer/mod_computer/mod_computer.c
- tests/auto/entry/modify_entry/modify_entry.c
- tests/auto/orgranizational_unit/add_ou/add_ou.c
- tests/samba-container/create-test-data.sh
Update test suite to better support windows ad 2012R2.
> fix: update test suite to better support windows ad 2012R2.

- README.md
- src/attribute.c
- src/common.h
- src/computer.c
- src/connection.c
- src/connection.h
- src/connection_state_machine.h
- src/directory.h
- src/domain.c
- src/domain.h
- src/domain_p.h
- src/entry_p.h
- src/group.c
- src/ldap_syntaxes.c
- src/organizational_unit.c
- src/request_queue.h
- src/schema.c
- src/schema_p.h
- src/user.c
Add more documentation.
- This change is a documentation update
> feat: add more documentation

- README.md
> fix: fix readme.md

- .gear/libdomain.spec
- src/entry.c
- tests/auto/search/search.c
Refactor search test to improve readability of search results.
> feat: refactor search test

- script/create-test-data.ps1
> feat: update powershell script

- README.md
Update documentation, add development packages installation instructions to README.md file.
> fix: add installation instructions to readme.md

- src/CMakeLists.txt
- src/ad_schema.c
- src/connection_state_machine.c
- src/schema.c
- src/schema_p.h
- tests/auto/schema/CMakeLists.txt
- tests/auto/schema/ad_schema.c
- tests/auto/schema/schema.c
- tests/auto/schema/schema_tests.h
Loads sub-schema from active directory.
> feat: implementation of active directory schema loading

- src/helper_p.h
In #80 i forgot to add `ld_talloc_realloc`. 
> feat: add missing `ld_talloc_realloc` into `helper_p.h`

- src/helper_p.h
We are replacing specific error messages with generic ones in this case, we need to think of a macro that can receive additional `error message` parameter.
_Originally posted by @august-alt in https://github.com/libdomain/libdomain/pull/87#pullrequestreview-2311627856_
> feat: add `ld_talloc_e` variant `in helper_p.h`  

- src/schema.c
Fixes memory leaks in directory service schemas.
- Bug fix
> fix: fixes memory leaks in directory service schemas

- src/helper_p.h
Correcting my mistake that I made in PR #88 
> fix: `...` -> `__VA_ARGS__` in `helper_p.h`

- src/schema.c
In libdomain, there are no memory allocation checks in many places. This PR should solve some of this.
This change is rather a change in the style of the code, in line with similar changes in memory refactoring
Continue of #80, #81, #82, #84, #86 and #87
Project: https://github.com/users/august-alt/projects/5/views/1?pane=issue&itemId=79701600
> style: replace `talloc` with `ld_talloc` in `schema.c`

- src/user.c
In libdomain, there are no memory allocation checks in many places. This PR should solve some of this.
This change is rather a change in the style of the code, in line with similar changes in memory refactoring
Continue of #80, #81, #82, #84, #86, #87 and #93
Project: https://github.com/users/august-alt/projects/5?pane=issue&itemId=79701635
> fix: replace `talloc` with `ld_talloc` in `user.c` with small refactor
